// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCABqlEmmFwGJ9QZ_Zd2ubrdf8fSiKZceg',
    appId: '1:861308737130:web:c750146dfe9d8236239c13',
    messagingSenderId: '861308737130',
    projectId: 'variety-dating-netweb',
    authDomain: 'variety-dating-netweb.firebaseapp.com',
    storageBucket: 'variety-dating-netweb.appspot.com',
    measurementId: 'G-W7MBY19Z1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wWOAco6lYvziHhALKulfahMd1brwkko',
    appId: '1:861308737130:android:e47c41da20a58842239c13',
    messagingSenderId: '861308737130',
    projectId: 'variety-dating-netweb',
    storageBucket: 'variety-dating-netweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ejbqM4OP8RKJmReJ2M3vpsQO3rs96dU',
    appId: '1:861308737130:ios:9382747486d67cad239c13',
    messagingSenderId: '861308737130',
    projectId: 'variety-dating-netweb',
    storageBucket: 'variety-dating-netweb.appspot.com',
    iosBundleId: 'com.example.varietyLanding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ejbqM4OP8RKJmReJ2M3vpsQO3rs96dU',
    appId: '1:861308737130:ios:9382747486d67cad239c13',
    messagingSenderId: '861308737130',
    projectId: 'variety-dating-netweb',
    storageBucket: 'variety-dating-netweb.appspot.com',
    iosBundleId: 'com.example.varietyLanding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCABqlEmmFwGJ9QZ_Zd2ubrdf8fSiKZceg',
    appId: '1:861308737130:web:80ae97a594529141239c13',
    messagingSenderId: '861308737130',
    projectId: 'variety-dating-netweb',
    authDomain: 'variety-dating-netweb.firebaseapp.com',
    storageBucket: 'variety-dating-netweb.appspot.com',
    measurementId: 'G-S8GSDRYCC6',
  );
}
